# Generated by Django 4.1.7 on 2023-02-22 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 15, 49, 44, 101317, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 15, 49, 44, 101317, tzinfo=datetime.timezone.utc)),
        ),
    ]
