# Generated by Django 4.1.7 on 2023-03-10 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 11, 0, 0, 990892, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 11, 0, 0, 990892, tzinfo=datetime.timezone.utc)),
        ),
    ]
